### ISSUE TITLE
Doesn't detect test files that start with `test_`

### ISSUE THREAD

**Issue by adam12** [ianks/nicetest#3]
If you use the `test_` naming for your test files, they are undetected by nicetest.

How do you feel about updating the glob to be similar to what minitest's test task uses? This will also unfortunately exclude `spec` users so I assume you might want a hook to be able to configure this eventually.

https://github.com/minitest/minitest/blob/dcee75dfb263e048377c59bad59104aba20a7647/lib/minitest/test_task.rb#L120-L121

**Comment by ianks** [comment]
I'd be totally cool with that!

**Comment by ianks** [comment]
https://github.com/ianks/nicetest/commit/9631bb46ad4046d4a0fcd30337ed3f9dbad2eb23 will release today ❤️
